repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8  # Use the latest version available
    hooks:
      - id: clang-format
        types_or: [c, c++, c#, cuda, java, objective-c, proto]